# Naunet config document

[general]
creation_time = "29/08/2022 22:25:24"
name = "naunet_klu_primordial"
description = "Example: primordial chemical network from KROME"
loads = []

[chemistry]
elements = ["e", "H", "D", "He"]
pseudo_elements = ["Photon"]
species = ["e-", "H", "H+", "H-", "D", "D+", "He", "He+", "He++", "H2", "H2+", "HD", "Photon"]
extra_species = []
network = ["primordial.krome"]
format = ["krome"]
heating = []
cooling = ["CIC_HI", "CIC_HeI", "CIC_HeII", "CIC_He_2S", "RC_HII", "RC_HeI", "RC_HeII", "RC_HeIII", "CEC_HI", "CEC_HeI", "CEC_HeII"]
ode_modifier = []

[chemistry.grain]
model = ""

[chemistry.binding_energy]

[chemistry.photon_yield]

[chemistry.shielding]

[chemistry.rate_modifier]

[ODEsolver]
solver = "cvode"
device = "cpu"
method = "sparse"

[summary]
num_of_species = 12
num_of_grains = 0
num_of_gas_species = 12
num_of_ice_species = 0
num_of_grain_species = 0
num_of_reactions = 38
list_of_species = ["He", "He++", "He+", "H2+", "D+", "D", "H-", "HD", "H", "H+", "H2", "e-"]
list_of_species_alias = ["HeI", "HeIII", "HeII", "H2II", "DII", "DI", "HM", "HDI", "HI", "HII", "H2I", "eM"]
list_of_gas_species = ["He", "He++", "He+", "H2+", "D+", "D", "H-", "HD", "H", "H+", "H2", "e-"]
list_of_ice_species = []
list_of_grain_species = []

